### ISSUE TITLE
Simplify setup in main `readme.md`

### ISSUE THREAD

**Issue by ChristinaLast** [AQ-AI/openaq-engine#44]
## Tasks
- [x] remove AWS setup
- [x] add quickstart to model training
- [x] Add Q and A "What if I dont have an AWS account?", "What if I dont know how to use google earth engine?"
