### ISSUE TITLE
Download all historic station data (as converting to a paid-for model)

### ISSUE THREAD

**Issue by ChristinaLast** [AQ-AI/openaq-engine#63]
# Tasks
- [X] adding test script 
- [x] test for one location "laos" where `country_id=98`
- [x] Create s3 buckets for storage
- [x] complete for all country locations
- [x] automate creation of s3 buckets with useful naming schema

**Comment by ChristinaLast** [comment]
@jit-1 are we merging this script? I believe you adjusted it when we needed to download historic data from openaq, but I am unaware of the location of the updated script.
